services:
  db:
    build:
      context: ./src/database/
    ports:
      - "${DB_PORT?}:1433"
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=${DB_SA_PASSWORD?}"
      - "DB_ADMIN=${DB_ADMIN?}"
      - "DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD?}"
      - "DB_USER=${DB_USER?}"
      - "DB_USER_PASSWORD=${DB_USER_PASSWORD?}"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - common

volumes:
  db-data:

networks:
  common:
    driver: bridge
