// <auto-generated />
using System;
using CaoHub.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CaoHub.Data.Migrations
{
    [DbContext(typeof(CaoHubDbContext))]
    partial class CaoHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Person", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Product", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountCalculationMethod")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountValue")
                        .HasPrecision(9, 5)
                        .HasColumnType("decimal(9,5)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("PaidByPersonId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrePaidAmount")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaidByPersonId");

                    b.HasIndex("StoreId");

                    b.ToTable("Receipt", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.ReceiptDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<decimal?>("UnitDiscount")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(9, 3)
                        .HasColumnType("decimal(9,3)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReceiptId");

                    b.ToTable("ReceiptDetail", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.ReceiptDetailPerson", b =>
                {
                    b.Property<int>("ReceiptDetailId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptDetailId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("ReceiptDetail_Person", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.ReceiptDetailTax", b =>
                {
                    b.Property<int>("ReceiptDetailId")
                        .HasColumnType("int");

                    b.Property<int>("TaxId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptDetailId", "TaxId");

                    b.HasIndex("TaxId");

                    b.ToTable("ReceiptDetail_Tax", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StoreCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreCategoryId");

                    b.ToTable("Store", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.StoreCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.HasKey("Id");

                    b.ToTable("StoreCategory", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalculationMethod")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Value")
                        .HasPrecision(9, 5)
                        .HasColumnType("decimal(9,5)");

                    b.HasKey("Id");

                    b.ToTable("Tax", "Facturio");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Receipt", b =>
                {
                    b.HasOne("CaoHub.Data.Models.Facturio.Person", "PaidByPerson")
                        .WithMany("Receipts")
                        .HasForeignKey("PaidByPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaoHub.Data.Models.Facturio.Store", "Store")
                        .WithMany("Receipts")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaidByPerson");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.ReceiptDetail", b =>
                {
                    b.HasOne("CaoHub.Data.Models.Facturio.Product", "Product")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CaoHub.Data.Models.Facturio.Receipt", "Receipt")
                        .WithMany("ReceiptDetails")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Receipt");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.ReceiptDetailPerson", b =>
                {
                    b.HasOne("CaoHub.Data.Models.Facturio.Person", "Person")
                        .WithMany("ReceiptDetailsPeople")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("CaoHub.Data.Models.Facturio.ReceiptDetail", "ReceiptDetail")
                        .WithMany("ReceiptDetailsPeople")
                        .HasForeignKey("ReceiptDetailId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("ReceiptDetail");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.ReceiptDetailTax", b =>
                {
                    b.HasOne("CaoHub.Data.Models.Facturio.ReceiptDetail", "ReceiptDetail")
                        .WithMany("ReceiptDetailsTaxes")
                        .HasForeignKey("ReceiptDetailId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.HasOne("CaoHub.Data.Models.Facturio.Tax", "Tax")
                        .WithMany("ReceiptDetailsTaxes")
                        .HasForeignKey("TaxId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("ReceiptDetail");

                    b.Navigation("Tax");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Store", b =>
                {
                    b.HasOne("CaoHub.Data.Models.Facturio.StoreCategory", "StoreCategory")
                        .WithMany("Stores")
                        .HasForeignKey("StoreCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreCategory");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Person", b =>
                {
                    b.Navigation("ReceiptDetailsPeople");

                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Product", b =>
                {
                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Receipt", b =>
                {
                    b.Navigation("ReceiptDetails");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.ReceiptDetail", b =>
                {
                    b.Navigation("ReceiptDetailsPeople");

                    b.Navigation("ReceiptDetailsTaxes");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Store", b =>
                {
                    b.Navigation("Receipts");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.StoreCategory", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("CaoHub.Data.Models.Facturio.Tax", b =>
                {
                    b.Navigation("ReceiptDetailsTaxes");
                });
#pragma warning restore 612, 618
        }
    }
}
