//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaoHub.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaoHub.Web.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAOHUB.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        public static string Apps {
            get {
                return ResourceManager.GetString("Apps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This entry will be deactivate and will no longer be accessible. However, data referencing this entry will remain intact..
        /// </summary>
        public static string DeleteDescription {
            get {
                return ResourceManager.GetString("DeleteDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must not exceed {1} characters..
        /// </summary>
        public static string ErrorMaxLength {
            get {
                return ResourceManager.GetString("ErrorMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {0} and {1}..
        /// </summary>
        public static string ErrorRange {
            get {
                return ResourceManager.GetString("ErrorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a value..
        /// </summary>
        public static string ErrorRequired {
            get {
                return ResourceManager.GetString("ErrorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additive.
        /// </summary>
        public static string Facturio_CalculationMethods_AdditiveValue {
            get {
                return ResourceManager.GetString("Facturio_CalculationMethods_AdditiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calculation method does not exist..
        /// </summary>
        public static string Facturio_CalculationMethods_ErrorNotExists {
            get {
                return ResourceManager.GetString("Facturio_CalculationMethods_ErrorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        public static string Facturio_CalculationMethods_PercentageBased {
            get {
                return ResourceManager.GetString("Facturio_CalculationMethods_PercentageBased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Method.
        /// </summary>
        public static string Facturio_CalculationMethods_Singular {
            get {
                return ResourceManager.GetString("Facturio_CalculationMethods_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TODO Description EN.
        /// </summary>
        public static string Facturio_Description {
            get {
                return ResourceManager.GetString("Facturio_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string Facturio_People {
            get {
                return ResourceManager.GetString("Facturio_People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you with to remove the person: {0}?.
        /// </summary>
        public static string Facturio_People_ConfirmDelete {
            get {
                return ResourceManager.GetString("Facturio_People_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Person.
        /// </summary>
        public static string Facturio_People_Create {
            get {
                return ResourceManager.GetString("Facturio_People_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Person.
        /// </summary>
        public static string Facturio_People_Delete {
            get {
                return ResourceManager.GetString("Facturio_People_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Person.
        /// </summary>
        public static string Facturio_People_Edit {
            get {
                return ResourceManager.GetString("Facturio_People_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A person with this name already exists..
        /// </summary>
        public static string Facturio_People_Name_ErrorExists {
            get {
                return ResourceManager.GetString("Facturio_People_Name_ErrorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a unique name for this person..
        /// </summary>
        public static string Facturio_People_Name_HelperText {
            get {
                return ResourceManager.GetString("Facturio_People_Name_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. John Doe.
        /// </summary>
        public static string Facturio_People_Name_Placeholder {
            get {
                return ResourceManager.GetString("Facturio_People_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Facturio_Products {
            get {
                return ResourceManager.GetString("Facturio_Products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to wish to remove the product: {0}?.
        /// </summary>
        public static string Facturio_Products_ConfirmDelete {
            get {
                return ResourceManager.GetString("Facturio_Products_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Product.
        /// </summary>
        public static string Facturio_Products_Create {
            get {
                return ResourceManager.GetString("Facturio_Products_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Product.
        /// </summary>
        public static string Facturio_Products_Delete {
            get {
                return ResourceManager.GetString("Facturio_Products_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string Facturio_Products_Edit {
            get {
                return ResourceManager.GetString("Facturio_Products_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a unique name for the product..
        /// </summary>
        public static string Facturio_Products_Name_HelperText {
            get {
                return ResourceManager.GetString("Facturio_Products_Name_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Banana.
        /// </summary>
        public static string Facturio_Products_Name_Placeholder {
            get {
                return ResourceManager.GetString("Facturio_Products_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipts.
        /// </summary>
        public static string Facturio_Receipts {
            get {
                return ResourceManager.GetString("Facturio_Receipts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        public static string Facturio_Receipts_DiscountAmount {
            get {
                return ResourceManager.GetString("Facturio_Receipts_DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid By.
        /// </summary>
        public static string Facturio_Receipts_PaidByPerson {
            get {
                return ResourceManager.GetString("Facturio_Receipts_PaidByPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepaid Amount.
        /// </summary>
        public static string Facturio_Receipts_PrepaidAmount {
            get {
                return ResourceManager.GetString("Facturio_Receipts_PrepaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Categories.
        /// </summary>
        public static string Facturio_StoreCategories {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove the category: {0}?.
        /// </summary>
        public static string Facturio_StoreCategories_ConfirmDelete {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Store Category.
        /// </summary>
        public static string Facturio_StoreCategories_Create {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Store Category.
        /// </summary>
        public static string Facturio_StoreCategories_Delete {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Store Category.
        /// </summary>
        public static string Facturio_StoreCategories_Edit {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store category does not exist..
        /// </summary>
        public static string Facturio_StoreCategories_ErrorNotExists {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_ErrorNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A store category with this name already exists..
        /// </summary>
        public static string Facturio_StoreCategories_Name_ErrorExists {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_Name_ErrorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a unique name for the category..
        /// </summary>
        public static string Facturio_StoreCategories_Name_HelperText {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_Name_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Groceries.
        /// </summary>
        public static string Facturio_StoreCategories_Name_Placeholder {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Category.
        /// </summary>
        public static string Facturio_StoreCategories_Singular {
            get {
                return ResourceManager.GetString("Facturio_StoreCategories_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stores.
        /// </summary>
        public static string Facturio_Stores {
            get {
                return ResourceManager.GetString("Facturio_Stores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove the store: {0}?.
        /// </summary>
        public static string Facturio_Stores_ConfirmDelete {
            get {
                return ResourceManager.GetString("Facturio_Stores_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Store.
        /// </summary>
        public static string Facturio_Stores_Create {
            get {
                return ResourceManager.GetString("Facturio_Stores_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Store.
        /// </summary>
        public static string Facturio_Stores_Delete {
            get {
                return ResourceManager.GetString("Facturio_Stores_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Store.
        /// </summary>
        public static string Facturio_Stores_Edit {
            get {
                return ResourceManager.GetString("Facturio_Stores_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A store with this name already exists..
        /// </summary>
        public static string Facturio_Stores_Name_ErrorExists {
            get {
                return ResourceManager.GetString("Facturio_Stores_Name_ErrorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a unique name for the store..
        /// </summary>
        public static string Facturio_Stores_Name_HelperText {
            get {
                return ResourceManager.GetString("Facturio_Stores_Name_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Tim Hortons.
        /// </summary>
        public static string Facturio_Stores_Name_Placeholder {
            get {
                return ResourceManager.GetString("Facturio_Stores_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Facturio_Stores_StoreCategoryId {
            get {
                return ResourceManager.GetString("Facturio_Stores_StoreCategoryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a category for this store..
        /// </summary>
        public static string Facturio_Stores_StoreCategoryId_HelperText {
            get {
                return ResourceManager.GetString("Facturio_Stores_StoreCategoryId_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Facturio_Taxes {
            get {
                return ResourceManager.GetString("Facturio_Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the calculation method for this tax..
        /// </summary>
        public static string Facturio_Taxes_CalculationMethod_HelperText {
            get {
                return ResourceManager.GetString("Facturio_Taxes_CalculationMethod_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to remove the tax: {0}?.
        /// </summary>
        public static string Facturio_Taxes_ConfirmDelete {
            get {
                return ResourceManager.GetString("Facturio_Taxes_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tax.
        /// </summary>
        public static string Facturio_Taxes_Create {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Tax.
        /// </summary>
        public static string Facturio_Taxes_Delete {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) Enter a description to better describe the tax..
        /// </summary>
        public static string Facturio_Taxes_Description_HelperText {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Description_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Goods &amp; Services Tax.
        /// </summary>
        public static string Facturio_Taxes_Description_Placeholder {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Description_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Tax.
        /// </summary>
        public static string Facturio_Taxes_Edit {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tax with this name already exists..
        /// </summary>
        public static string Facturio_Taxes_Name_ErrorExists {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Name_ErrorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a unique name for this tax..
        /// </summary>
        public static string Facturio_Taxes_Name_HelperText {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Name_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. GST.
        /// </summary>
        public static string Facturio_Taxes_Name_Placeholder {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Name_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the value for this tax..
        /// </summary>
        public static string Facturio_Taxes_Value_HelperText {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Value_HelperText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. 14.975.
        /// </summary>
        public static string Facturio_Taxes_Value_Placeholder {
            get {
                return ResourceManager.GetString("Facturio_Taxes_Value_Placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facturio.
        /// </summary>
        public static string Facturio_Title {
            get {
                return ResourceManager.GetString("Facturio_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
    }
}
